/// Linker layout for a ROM-loaded, all-SRAM ESP32-S3 image.
///
/// The Cortex-M generator in Layout.fs emits two regions, FLASH and RAM, and
/// copies `.data` from the first to the second at runtime via `AT>`. Neither
/// half of that shape holds here:
///
///  * There is no executable flash region. The mask ROM loads every segment
///    into SRAM and jumps, so `.data` has no load address distinct from its
///    virtual address -- the ROM loader has already done the copy by the time
///    the entry symbol runs. Only `.bss` needs zeroing.
///
///  * The SRAM is three banks and the middle one is DUAL-MAPPED: SRAM1 answers
///    to the instruction bus at 0x4037_8000 and to the data bus at
///    0x3FC8_8000, and those are the same silicon. A script that fills an IRAM
///    region upward from its base and a DRAM region upward from its base puts
///    `.text` and `.data` on top of each other, with no diagnostic from the
///    linker: the addresses do not overlap, only the memory does.
///
/// The partition is therefore explicit. `Sram1InstructionBytes` says how much
/// of the shared bank the instruction side takes; the data side starts after
/// it. The generated script asserts the split holds, so a bad declaration
/// fails at link time rather than on the board.
module BackEnd.MCU.XtensaLayout

open System.IO
open Core.Types.Pipeline

let origin (space: BAREWire.Platform.MemorySpace) =
    space.Base |> Option.defaultWith (fun () -> failwith ("No base for " + space.Name))

/// The instruction and data windows this image may use, after partitioning the
/// shared bank. Computed once so the script and the image verifier agree.
type Windows = {
    /// Instruction bus: SRAM0 plus the instruction share of SRAM1. These are
    /// contiguous in the instruction address space (SRAM0 ends exactly where
    /// SRAM1 begins), so they present as one region.
    IramOrigin: int64
    IramBytes: int64
    /// Data bus: the data share of SRAM1 plus all of SRAM2, also contiguous.
    DramOrigin: int64
    DramBytes: int64
}

/// Partition the shared bank and check every premise the split relies on.
let windows (target: XtensaTarget) : Windows =
    let sram0, sram1, sram1Data, sram2 = target.Sram0, target.Sram1, target.Sram1Data, target.Sram2
    let instructionShare = int64 target.Image.Sram1InstructionBytes

    if instructionShare < 0L || instructionShare > sram1.Capacity then
        failwithf "Sram1InstructionBytes %d is outside the shared bank's %d bytes" instructionShare sram1.Capacity
    // The ROM loader copies words, and the vector block needs a 1024-byte
    // boundary inside the instruction window.
    if instructionShare % int64 target.Image.VectorAlignment <> 0L then
        failwithf "Sram1InstructionBytes %d must be a multiple of the %d-byte vector alignment so the data side starts aligned"
            instructionShare target.Image.VectorAlignment
    // The alias must be declared as an alias, or capacity is counted twice.
    if sram1Data.Capacity <> 0L then
        failwithf "%s is the data-bus alias of %s and must declare Capacity = 0; it declares %d"
            sram1Data.Name sram1.Name sram1Data.Capacity
    // SRAM0 must abut SRAM1 on the instruction bus for one region to cover both.
    if origin sram0 + sram0.Capacity <> origin sram1 then
        failwithf "%s does not abut %s on the instruction bus" sram0.Name sram1.Name
    // The data share must abut SRAM2 on the data bus for the same reason.
    if origin sram1Data + sram1.Capacity <> origin sram2 then
        failwithf "%s does not abut %s on the data bus" sram1Data.Name sram2.Name

    { IramOrigin = origin sram0
      IramBytes = sram0.Capacity + instructionShare
      DramOrigin = origin sram1Data + instructionShare
      DramBytes = (sram1.Capacity - instructionShare) + sram2.Capacity }

let generate (target: XtensaTarget) destination =
    Directory.CreateDirectory destination |> ignore
    let w = windows target
    let image = target.Image
    let stackTop = w.DramOrigin + w.DramBytes
    let stackBottom = stackTop - int64 image.StackBytes
    if image.StackBytes <= 0 || int64 image.StackBytes >= w.DramBytes || image.StackBytes % 16 <> 0 then
        failwith "Invalid Xtensa stack reservation; the call ABI requires 16-byte stack alignment"

    // The offset of the data window inside the shared bank, used by the script's
    // non-overlap assertion. Expressed as an instruction-bus address so the two
    // views can be compared in one arithmetic domain.
    let sharedBankInstructionBase = origin target.Sram1
    let dataShareAsInstructionAddress = sharedBankInstructionBase + int64 image.Sram1InstructionBytes

    let script =
        sprintf """/* Generated by Composer from BAREWire declarations; do not edit.
 *
 * All-SRAM image. The Espressif mask ROM loads each segment to its address and
 * jumps to %s, so there is no load-address/virtual-address split and no
 * runtime .data copy: only .bss is zeroed by startup.
 *
 * SRAM1 is dual-mapped. IRAM holds SRAM0 plus the first 0x%X bytes of SRAM1;
 * DRAM holds the rest of SRAM1 plus SRAM2. The final ASSERT proves the two
 * windows do not name the same silicon.
 */
ENTRY(%s)
MEMORY {
  IRAM (rx) : ORIGIN = 0x%X, LENGTH = 0x%X
  DRAM (rw) : ORIGIN = 0x%X, LENGTH = 0x%X
}
__stack_top = 0x%X;
__stack_bottom = 0x%X;
__shared_bank_instruction_base = 0x%X;
__shared_bank_data_split = 0x%X;
SECTIONS {
  /* VECBASE ignores its low bits, so the vector block leads the image at a
   * %d-byte boundary. It is code, not a table of addresses. */
  .vectors ORIGIN(IRAM) : ALIGN(%d) { KEEP(*(.vectors)) KEEP(*(.vectors.*)) } > IRAM
  .text : ALIGN(4) {
    *(.text*)
    *(.literal*)     /* Xtensa literal pools: L32R operands, not instructions */
    *(.rodata*)
  } > IRAM
  __iram_end = .;

  /* Initialized data is placed, not copied: the ROM loader delivers it. */
  .data ORIGIN(DRAM) : ALIGN(16) {
    __data_start = .; *(.data*) . = ALIGN(4); __data_end = .;
  } > DRAM
  .bss (NOLOAD) : ALIGN(16) {
    __bss_start = .; *(.bss*) *(COMMON) . = ALIGN(4); __bss_end = .;
  } > DRAM
  .noinit (NOLOAD) : ALIGN(16) { *(.noinit*) } > DRAM
  __dram_end = .;
  .stack __stack_bottom (NOLOAD) : { . += %d; } > DRAM
  /DISCARD/ : { *(.comment) *(.note*) *(.eh_frame*) *(.xt.prop*) *(.xt.lit*) }
}
ASSERT(SIZEOF(.vectors) == %d, "Wrong vector block size")
ASSERT((ADDR(.vectors) & (%d - 1)) == 0, "Vector block is not VECBASE-aligned")
ASSERT(__dram_end <= __stack_bottom, "Data and stack collide")
ASSERT(__iram_end <= ORIGIN(IRAM) + LENGTH(IRAM), "IRAM overflow")
/* The dual-mapping check: instruction-side use must stop before the byte of
 * the shared bank where data-side use begins. Without this, .text and .data
 * silently occupy the same SRAM at two different addresses. */
ASSERT(__iram_end <= __shared_bank_data_split,
       "IRAM use crosses into the data side of the shared SRAM bank")
"""
            image.EntrySymbol image.Sram1InstructionBytes image.EntrySymbol
            w.IramOrigin w.IramBytes w.DramOrigin w.DramBytes
            stackTop stackBottom
            sharedBankInstructionBase dataShareAsInstructionAddress
            image.VectorAlignment image.VectorAlignment
            image.StackBytes
            target.Vectors.Layout.Size image.VectorAlignment

    File.WriteAllText(Path.Combine(destination, "memory.ld"), script)
    // Startup assembly reads these rather than hardcoding the same numbers.
    File.WriteAllText(
        Path.Combine(destination, "layout.inc"),
        sprintf ".set VECTOR_BYTES, %d\n.set VECTOR_ALIGNMENT, %d\n.set STACK_BYTES, %d\n"
            target.Vectors.Layout.Size image.VectorAlignment image.StackBytes)
    Tools.writeJson (Path.Combine(destination, "layout.json"))
        {| platform = target.PlatformId
           iramOrigin = w.IramOrigin; iramBytes = w.IramBytes
           dramOrigin = w.DramOrigin; dramBytes = w.DramBytes
           sharedBankInstructionBytes = image.Sram1InstructionBytes
           sharedBankCapacity = target.Sram1.Capacity
           stackBottom = stackBottom; stackTop = stackTop
           vectorBytes = target.Vectors.Layout.Size
           vectorAlignment = image.VectorAlignment
           dataCopiedByRomLoader = true |}
    w
